src/TurnTrackerAspNetCore/Entities/Task.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TurnTrackerAspNetCore.Entities
{
    public class Task
    {
        public long Id { get; set; }

        [Required, MaxLength(100)]
        public string Name { get; set; }

        public bool TeamBased { get; set; }
    }
}

src/TurnTrackerAspNetCore/ViewModels/Task/EditTaskViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using TurnTrackerAspNetCore.Entities;

namespace TurnTrackerAspNetCore.ViewModels.Task
{
    public class EditTaskViewModel
    {
        [Required, MaxLength(100)]
        public string Name { get; set; }

        [Required]
        public decimal Period { get; set; }

        [Required]
        public PeriodUnit Unit { get; set; }

        [Display(Name = "Team Based")]
        public bool TeamBased { get; set; }

        public IEnumerable<string> Participants { get; set; }

        public List<SelectListItem> Users { get; set; }

        public long Id { get; set; }

        [Required]
        public string Owner { get; set; }
    }
}

src/TurnTrackerAspNetCore/ViewModels/Task/TaskDetailsViewModel.cs
using System.Collections.Generic;
using TurnTrackerAspNetCore.Entities;

namespace TurnTrackerAspNetCore.ViewModels.Task
{
    public class TaskDetailsViewModel
    {
        public TrackedTask Task { get; set; }
        public List<UserCountViewModel> Counts { get; set; }
        public int MaxTurns { get; set; }
        public bool CanTakeTurn { get; set; }
        public bool CanDeleteTask { get; set; }
        public string Error { get; set; }
    }
}

src/TurnTrackerAspNetCore/ViewModels/Task/TasksViewModel.cs
using System.Collections.Generic;
using TurnTrackerAspNetCore.Entities;

namespace TurnTrackerAspNetCore.ViewModels.Task
{
    public class TasksViewModel
    {
        public Dictionary<TrackedTask,TurnCount> TaskCounts { get; set; }
        public string Error { get; set; }
    }
}

src/TurnTrackerAspNetCore/ViewModels/Task/UserCountViewModel.cs
using TurnTrackerAspNetCore.Entities;

namespace TurnTrackerAspNetCore.ViewModels.Task
{
    public class UserCountViewModel
    {
        public string Name { get; set; }
        public int TotalTurns { get; set; }

        public UserCountViewModel(TurnCount count)
        {
            Name = count.DisplayName ?? count.UserName;
            TotalTurns = count.TotalTurns;
        }
    }
}

src/TurnTrackerAspNetCore/ViewModels/TasksViewModel.cs
using System.Collections.Generic;
using TurnTrackerAspNetCore.Entities;

namespace TurnTrackerAspNetCore.ViewModels
{
    public class TasksViewModel
    {
        public Dictionary<TrackedTask,TurnCount> TaskCounts { get; set; }
        public string Error { get; set; }
    }
}

src/TurnTrackerAspNetCore/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace TurnTrackerAspNetCore.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        // stash this here for now, maybe move it to another controller at some point
        public IActionResult Error(string code)
        {
            return View(nameof(Error), code);
        }
    }
}

src/TurnTrackerAspNetCore/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TurnTrackerAspNetCore.Entities;
using TurnTrackerAspNetCore.Services;
using TurnTrackerAspNetCore.Services.Data;
using TurnTrackerAspNetCore.ViewModels.Task;

namespace TurnTrackerAspNetCore.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        private readonly ITaskData _taskData;
        private readonly UserManager<User> _userManager;
        private readonly IAuthorizationService _authorizationService;

        public TaskController(UserManager<User> userManager, ITaskData taskData, IAuthorizationService authorizationService)
        {
            _userManager = userManager;
            _taskData = taskData;
            _authorizationService = authorizationService;
        }
        
        public IActionResult Index(string error = null)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var counts = _taskData.GetTurnCounts(userId);
            var tasks = _taskData.GetParticipations(userId).Union(_taskData.GetAllTasks().Where(x => x.UserId == userId)).ToList();
            var latest = _taskData.GetLatestTurns(tasks.Select(x => x.Id).ToArray()).ToList();
            var taskCounts = new Dictionary<TrackedTask, TurnCount>();
            foreach (var task in tasks)
            {
                task.PopulateLatestTurnInfo(counts, taskCounts, latest);
            }

            return View("Tasks", new TasksViewModel { TaskCounts = taskCounts, Error = error });
        }
        
        public async Task<IActionResult> Details(long id, string error = null)
        {
            var task = _taskData.GetTaskDetails(id);
            if (null == task)
            {
                return new NotFoundResult();
            }
            if (!await _authorizationService.AuthorizeAsync(User, task, nameof(Policies.CanAccessTask)))
            {
                return new ChallengeResult();
            }

            var userId = _userManager.GetUserId(HttpContext.User);

            var counts = _taskData.GetTurnCounts(id).ToList();
            task.PopulateLatestTurnInfo(
                new Dictionary<long, List<TurnCount>> { { task.Id, counts } },
                new Dictionary<TrackedTask, TurnCount>(),
                task.Turns);
            var maxTurns = counts.Max(x => x.TotalTurns, 0);

            var model = new TaskDetailsViewModel
            {
                Task = task,
                Counts = counts.Select(x => new UserCountViewModel(x)).ToList(),
                MaxTurns = maxTurns,
                CanTakeTurn = task.Participants.Any(x => x.UserId == userId),
                CanDeleteTask = task.UserId == userId,
                Error = error
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var owner = _userManager.GetUserId(HttpContext.User);
            return View(new EditTaskViewModel
            {
                Owner = owner,
                Users = _taskData.GetAllUsers().Select(x => new SelectListItem
                {
                    Value = x.Id,
                    Text = x.DisplayName == null ? $"{x.UserName}" : $"{x.DisplayName} ({x.UserName})",
                    Selected = owner == x.Id
                }).ToList()
            });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Create(EditTaskViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var userId = _userManager.GetUserId(HttpContext.User);
            var task = new TrackedTask
            {
                Name = model.Name,
                Period = model.Period,
                Unit = model.Unit,
                TeamBased = model.TeamBased,
                UserId = userId
            };
            var newTask = _taskData.Add(task);
            // ensure the creator is a participant
            newTask.Participants =
                new[] {userId}.Union(model.Participants ?? new List<string>())
                    .Distinct()
                    .Select(x => new Participant {UserId = x, TaskId = newTask.Id})
                    .ToList();
            _taskData.Commit();
            return RedirectToAction(nameof(Details), new { id = newTask.Id });
        }


        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            var task = _taskData.GetTaskDetails(id);

            if (null == task)
            {
                return new NotFoundResult();
            }
            if (!await _authorizationService.AuthorizeAsync(User, task, nameof(Policies.CanAccessTask)))
            {
                return new ChallengeResult();
            }
            
            var participantIds = task.Participants?.Select(x => x.UserId).ToList() ?? new List<string>();
            var model = new EditTaskViewModel
            {
                Id = task.Id,
                Name = task.Name,
                Period = task.Period,
                Unit = task.Unit,
                TeamBased = task.TeamBased,
                Owner = task.UserId,
                Users = _taskData.GetAllUsers().Select(x => new SelectListItem
                {
                    Value = x.Id,
                    Text = x.DisplayName == null ? $"{x.UserName}" : $"{x.DisplayName} ({x.UserName})",
                    Selected = participantIds.Contains(x.Id)
                }).ToList()
            };
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, EditTaskViewModel model)
        {
            var task = _taskData.GetTaskDetails(id);

            if (null == task)
            {
                return new NotFoundResult();
            }
            if (!await _authorizationService.AuthorizeAsync(User, task, nameof(Policies.CanAccessTask)))
            {
                return new ChallengeResult();
            }

            if (!ModelState.IsValid)
            {
                return View(task);
            }
            task.Period = model.Period;
            task.TeamBased = model.TeamBased;
            task.Unit = model.Unit;
            task.UserId = model.Owner;
            task.Name = model.Name;
            model.Participants = model.Participants ?? new List<string>();

            // update participants and give you users the max count as an offset
            var counts = _taskData.GetTurnCounts(task.Id).ToList();
            var max = counts.Max(x => x.TotalTurns, 0);
            task.Participants.RemoveAll(x => !model.Participants.Contains(x.UserId));
            foreach (var newId in model.Participants.Except(task.Participants.Select(x => x.UserId)))
            {
                var offset = max - task.Turns.Count(x => x.UserId == newId);
                task.Participants.Add(new Participant { TaskId = id, UserId = newId, Offset = offset });
            }

            task.Modified = DateTimeOffset.UtcNow;
            _taskData.Commit();
            return RedirectToAction(nameof(Details), new { id = task.Id });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(long id)
        {
            var task = _taskData.GetTaskDetails(id);

            if (null == task)
            {
                return new NotFoundResult();
            }
            if (!await _authorizationService.AuthorizeAsync(User, task, nameof(Policies.CanDeleteTask)))
            {
                return new ChallengeResult();
            }

            _taskData.DeleteTask(task);
            _taskData.Commit();
            return RedirectToAction(nameof(Index));
        }
    }
}

src/TurnTrackerAspNetCore/Views/Shared/AccessDenied.cshtml
@{
    ViewBag.Title = "Access Denied";
}
<h1>ಠ_ಠ</h1>
<br />
<p>Access Denied</p>

src/TurnTrackerAspNetCore/Views/Shared/Tasks.cshtml
@using System.Threading.Tasks
@model TurnTrackerAspNetCore.ViewModels.Task.TasksViewModel
@if (!string.IsNullOrWhiteSpace(Model.Error))
{
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>@Model.Error
    </div>
}
<h1>
    <span>Tasks</span>
    @if (User.Identity.IsAuthenticated)
    {
        <span> <a class="btn btn-sm btn-primary" asp-controller="Task" asp-action="Create"><span class="glyphicon glyphicon-plus"></span></a></span>
    }
</h1>
@if (Model.TaskCounts.Count == 0)
{
    <p>No tasks</p>
}
else
{
    <table class="table table-striped table-condensed table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Team Based</th>
                <th>Period</th>
                <th>Next</th>
                <th>Time</th>
                <th></th>
            </tr>
        </thead>
        @foreach (var kvp in Model.TaskCounts)
        {
            @Html.Partial("_Task", kvp)
        }
    </table>
}

src/TurnTrackerAspNetCore/Views/Shared/_Layout.cshtml
@using TurnTrackerAspNetCore.Middleware
@using TurnTrackerAspNetCore.Services.Settings
@inject ISiteSettings SiteSettings
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@(ViewBag.Title ?? SiteSettings.Settings.General.Name)</title>
    <environment Names="Development">
        <link href="/lib/css/bootstrap.css" rel="stylesheet" />
    </environment>
    <environment Names="Staging,Production">
        <link href="/lib/css/bootstrap.min.css" rel="stylesheet" />
    </environment>
    <link href="/css/site.min.css" rel="stylesheet"/>
    <link href="/lib/css/bootstrap-datetimepicker.min.css" rel="stylesheet"/>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">@SiteSettings.Settings.General.Name</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a asp-controller="About" asp-action="Index">About</a></li>
                @if (User.IsInRole("Admin"))
                {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Admin" asp-action="Tasks">Tasks</a></li>
                            <li><a asp-controller="Admin" asp-action="Users">Users</a></li>
                            <li><a asp-controller="Admin" asp-action="Invites">Invites</a></li>
                            <li><a asp-controller="Admin" asp-action="SiteSettings">Settings</a></li>
                            <li><a asp-controller="Admin" asp-action="PreviewNotifications">Preview</a></li>
                            <li><a asp-controller="Admin" asp-action="Hangfire">Hangfire</a></li>
                            <li><a asp-controller="Admin" asp-action="Test">Cron Helper</a></li>
                        </ul>
                    </li>
                }
            </ul>
            @await Component.InvokeAsync("LoginLogout")
        </div>
    </div>
</nav>
<div class="container">
    @RenderBody()
    <footer>
        @RenderSection("footer", required: false)
        <div class="pull-right">Build @(Microsoft.Extensions.PlatformAbstractions.PlatformServices.Default.Application.ApplicationVersion)</div>
    </footer>
</div>
<script type="text/javascript">
    var d = new Date();
    d.setDate(d.getDate() + 1);
    document.cookie = '@TimezoneOffsetReader.CookieKey=' + d.getTimezoneOffset() + '; expires=' + d + '; path=/';
</script>
<environment Names="Development">
    <script src="/lib/js/jquery.js"></script>
    <script src="/lib/js/bootstrap.js"></script>
</environment>
<environment Names="Staging,Production">
    <script src="/lib/js/jquery.min.js"></script>
    <script src="/lib/js/bootstrap.min.js"></script>
</environment>
<script src="/lib/js/moment.min.js"></script>
<script src="/lib/js/jquery.validate.js"></script>
<script src="/lib/js/jquery.validate.unobtrusive.js"></script>
<script src="/lib/js/bootstrap-datetimepicker.min.js"></script>
<script src="/js/site.js"></script>
</body>
</html>

src/TurnTrackerAspNetCore/Views/Shared/_Task.cshtml
@model KeyValuePair<TrackedTask,TurnCount>
@{
    var task = Model.Key;
    var count = Model.Value;
}

<tr class="task-row @(task.Overdue ? "danger" : "")">
    <td>@task.Name</td>
    <td>@task.TeamBased</td>
    <td>@(task.Period == 0m ? "Non-Periodic" : $"{task.Period} {task.Unit}")</td>
    <td>
        @if (!task.TeamBased)
        {
            @(count?.DisplayName ?? count?.UserName ?? "")
        }
    </td>
    <td>
        @if (task.Overdue)
        {
            <strong>@task.DueTimeSpan.ToString(@"hh\:mm\:ss") overdue</strong>
        }
        else
        {
            <span>@task.DueTimeSpan.ToString(@"hh\:mm\:ss")</span>
        }
    </td>
    <td><a class="btn btn-default btn-xs details-btn" asp-controller="Task" asp-action="Details" asp-route-id="@task.Id">Details</a></td>
</tr>