src/TurnTrackerAspNetCore/Entities/Task.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TurnTrackerAspNetCore.Entities
{
    public class Task
    {
        public long Id { get; set; }

        [Required, MaxLength(100)]
        public string Name { get; set; }

        public bool TeamBased { get; set; }
    }
}

src/TurnTrackerAspNetCore/Entities/Turn.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TurnTrackerAspNetCore.Entities
{
    public class Turn
    {
        [Key]
        public long Id { get; set; }

        [Required]
        public long TaskId { get; set; }
        public TrackedTask Task { get; set; }

        [Required]
        public string UserId { get; set; }
        public User User { get; set; }
        
        public DateTimeOffset Taken { get; set; }
        
        public DateTimeOffset Created { get; set; }
        
        public DateTimeOffset Modified { get; set; }
    }
}

src/TurnTrackerAspNetCore/ViewModels/Task/EditTaskViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using TurnTrackerAspNetCore.Entities;

namespace TurnTrackerAspNetCore.ViewModels.Task
{
    public class EditTaskViewModel
    {
        [Required, MaxLength(100)]
        public string Name { get; set; }

        [Required]
        public decimal Period { get; set; }

        [Required]
        public PeriodUnit Unit { get; set; }

        [Display(Name = "Team Based")]
        public bool TeamBased { get; set; }

        public IEnumerable<string> Participants { get; set; }

        public List<SelectListItem> Users { get; set; }

        public long Id { get; set; }

        [Required]
        public string Owner { get; set; }
    }
}

src/TurnTrackerAspNetCore/ViewModels/Task/TaskDetailsViewModel.cs
using System.Collections.Generic;
using TurnTrackerAspNetCore.Entities;

namespace TurnTrackerAspNetCore.ViewModels.Task
{
    public class TaskDetailsViewModel
    {
        public TrackedTask Task { get; set; }
        public List<UserCountViewModel> Counts { get; set; }
        public int MaxTurns { get; set; }
        public bool CanTakeTurn { get; set; }
        public bool CanDeleteTask { get; set; }
        public string Error { get; set; }
    }
}

src/TurnTrackerAspNetCore/ViewModels/Task/TasksViewModel.cs
using System.Collections.Generic;
using TurnTrackerAspNetCore.Entities;

namespace TurnTrackerAspNetCore.ViewModels.Task
{
    public class TasksViewModel
    {
        public Dictionary<TrackedTask,TurnCount> TaskCounts { get; set; }
        public string Error { get; set; }
    }
}

src/TurnTrackerAspNetCore/ViewModels/Task/UserCountViewModel.cs
using TurnTrackerAspNetCore.Entities;

namespace TurnTrackerAspNetCore.ViewModels.Task
{
    public class UserCountViewModel
    {
        public string Name { get; set; }
        public int TotalTurns { get; set; }

        public UserCountViewModel(TurnCount count)
        {
            Name = count.DisplayName ?? count.UserName;
            TotalTurns = count.TotalTurns;
        }
    }
}

src/TurnTrackerAspNetCore/ViewModels/TasksViewModel.cs
using System.Collections.Generic;
using TurnTrackerAspNetCore.Entities;

namespace TurnTrackerAspNetCore.ViewModels
{
    public class TasksViewModel
    {
        public Dictionary<TrackedTask,TurnCount> TaskCounts { get; set; }
        public string Error { get; set; }
    }
}

src/TurnTrackerAspNetCore/ViewModels/Turn/EditTurnViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TurnTrackerAspNetCore.ViewModels.Turn
{
    public class EditTurnViewModel
    {
        [DataType(DataType.DateTime)]
        public DateTimeOffset Taken { get; set; }
    }
}

src/TurnTrackerAspNetCore/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TurnTrackerAspNetCore.Entities;
using TurnTrackerAspNetCore.Services;
using TurnTrackerAspNetCore.Services.Data;
using TurnTrackerAspNetCore.ViewModels.Task;

namespace TurnTrackerAspNetCore.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        private readonly ITaskData _taskData;
        private readonly UserManager<User> _userManager;
        private readonly IAuthorizationService _authorizationService;

        public TaskController(UserManager<User> userManager, ITaskData taskData, IAuthorizationService authorizationService)
        {
            _userManager = userManager;
            _taskData = taskData;
            _authorizationService = authorizationService;
        }
        
        public IActionResult Index(string error = null)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var counts = _taskData.GetTurnCounts(userId);
            var tasks = _taskData.GetParticipations(userId).Union(_taskData.GetAllTasks().Where(x => x.UserId == userId)).ToList();
            var latest = _taskData.GetLatestTurns(tasks.Select(x => x.Id).ToArray()).ToList();
            var taskCounts = new Dictionary<TrackedTask, TurnCount>();
            foreach (var task in tasks)
            {
                task.PopulateLatestTurnInfo(counts, taskCounts, latest);
            }

            return View("Tasks", new TasksViewModel { TaskCounts = taskCounts, Error = error });
        }
        
        public async Task<IActionResult> Details(long id, string error = null)
        {
            var task = _taskData.GetTaskDetails(id);
            if (null == task)
            {
                return new NotFoundResult();
            }
            if (!await _authorizationService.AuthorizeAsync(User, task, nameof(Policies.CanAccessTask)))
            {
                return new ChallengeResult();
            }

            var userId = _userManager.GetUserId(HttpContext.User);

            var counts = _taskData.GetTurnCounts(id).ToList();
            task.PopulateLatestTurnInfo(
                new Dictionary<long, List<TurnCount>> { { task.Id, counts } },
                new Dictionary<TrackedTask, TurnCount>(),
                task.Turns);
            var maxTurns = counts.Max(x => x.TotalTurns, 0);

            var model = new TaskDetailsViewModel
            {
                Task = task,
                Counts = counts.Select(x => new UserCountViewModel(x)).ToList(),
                MaxTurns = maxTurns,
                CanTakeTurn = task.Participants.Any(x => x.UserId == userId),
                CanDeleteTask = task.UserId == userId,
                Error = error
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var owner = _userManager.GetUserId(HttpContext.User);
            return View(new EditTaskViewModel
            {
                Owner = owner,
                Users = _taskData.GetAllUsers().Select(x => new SelectListItem
                {
                    Value = x.Id,
                    Text = x.DisplayName == null ? $"{x.UserName}" : $"{x.DisplayName} ({x.UserName})",
                    Selected = owner == x.Id
                }).ToList()
            });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Create(EditTaskViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var userId = _userManager.GetUserId(HttpContext.User);
            var task = new TrackedTask
            {
                Name = model.Name,
                Period = model.Period,
                Unit = model.Unit,
                TeamBased = model.TeamBased,
                UserId = userId
            };
            var newTask = _taskData.Add(task);
            // ensure the creator is a participant
            newTask.Participants =
                new[] {userId}.Union(model.Participants ?? new List<string>())
                    .Distinct()
                    .Select(x => new Participant {UserId = x, TaskId = newTask.Id})
                    .ToList();
            _taskData.Commit();
            return RedirectToAction(nameof(Details), new { id = newTask.Id });
        }


        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            var task = _taskData.GetTaskDetails(id);

            if (null == task)
            {
                return new NotFoundResult();
            }
            if (!await _authorizationService.AuthorizeAsync(User, task, nameof(Policies.CanAccessTask)))
            {
                return new ChallengeResult();
            }
            
            var participantIds = task.Participants?.Select(x => x.UserId).ToList() ?? new List<string>();
            var model = new EditTaskViewModel
            {
                Id = task.Id,
                Name = task.Name,
                Period = task.Period,
                Unit = task.Unit,
                TeamBased = task.TeamBased,
                Owner = task.UserId,
                Users = _taskData.GetAllUsers().Select(x => new SelectListItem
                {
                    Value = x.Id,
                    Text = x.DisplayName == null ? $"{x.UserName}" : $"{x.DisplayName} ({x.UserName})",
                    Selected = participantIds.Contains(x.Id)
                }).ToList()
            };
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, EditTaskViewModel model)
        {
            var task = _taskData.GetTaskDetails(id);

            if (null == task)
            {
                return new NotFoundResult();
            }
            if (!await _authorizationService.AuthorizeAsync(User, task, nameof(Policies.CanAccessTask)))
            {
                return new ChallengeResult();
            }

            if (!ModelState.IsValid)
            {
                return View(task);
            }
            task.Period = model.Period;
            task.TeamBased = model.TeamBased;
            task.Unit = model.Unit;
            task.UserId = model.Owner;
            task.Name = model.Name;
            model.Participants = model.Participants ?? new List<string>();

            // update participants and give you users the max count as an offset
            var counts = _taskData.GetTurnCounts(task.Id).ToList();
            var max = counts.Max(x => x.TotalTurns, 0);
            task.Participants.RemoveAll(x => !model.Participants.Contains(x.UserId));
            foreach (var newId in model.Participants.Except(task.Participants.Select(x => x.UserId)))
            {
                var offset = max - task.Turns.Count(x => x.UserId == newId);
                task.Participants.Add(new Participant { TaskId = id, UserId = newId, Offset = offset });
            }

            task.Modified = DateTimeOffset.UtcNow;
            _taskData.Commit();
            return RedirectToAction(nameof(Details), new { id = task.Id });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(long id)
        {
            var task = _taskData.GetTaskDetails(id);

            if (null == task)
            {
                return new NotFoundResult();
            }
            if (!await _authorizationService.AuthorizeAsync(User, task, nameof(Policies.CanDeleteTask)))
            {
                return new ChallengeResult();
            }

            _taskData.DeleteTask(task);
            _taskData.Commit();
            return RedirectToAction(nameof(Index));
        }
    }
}

src/TurnTrackerAspNetCore/Controllers/TurnController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TurnTrackerAspNetCore.Entities;
using TurnTrackerAspNetCore.Services;
using TurnTrackerAspNetCore.Services.Data;
using TurnTrackerAspNetCore.ViewModels.Turn;

namespace TurnTrackerAspNetCore.Controllers
{
    [Authorize]
    public class TurnController : Controller
    {
        private readonly ITaskData _taskData;
        private readonly UserManager<User> _userManager;
        private readonly IAuthorizationService _authorizationService;

        public TurnController(ITaskData taskData, UserManager<User> userManager, IAuthorizationService authorizationService)
        {
            _taskData = taskData;
            _userManager = userManager;
            _authorizationService = authorizationService;
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Take(long id, DateTimeOffset? time = null)
        {
            var task = _taskData.GetTaskDetails(id);

            if (null == task)
            {
                return new NotFoundResult();
            }
            if (!await _authorizationService.AuthorizeAsync(User, task, nameof(Policies.CanAccessTask)))
            {
                return new ChallengeResult();
            }
            // TODO use timezone, this probably only works because the server is currently in the same time zone when developing
            var userId = _userManager.GetUserId(HttpContext.User);
            var turn = new Turn {UserId = userId};
            if (time.HasValue && time.Value < DateTimeOffset.UtcNow.AddMinutes(30))
            {
                // don't allow a time very far into the future
                turn.Taken = time.Value;
            }
            task.Turns.Add(turn);
            _taskData.Commit();
            return RedirectToAction(nameof(TaskController.Details), "Task", new { id });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(long id)
        {
            var turn = _taskData.GetTurn(id);
            if (null == turn)
            {
                return new NotFoundResult();
            }

            var task = _taskData.GetTaskDetails(turn.TaskId);
            if (null == task)
            {
                return new NotFoundResult();
            }
            if (!await _authorizationService.AuthorizeAsync(User, task, nameof(Policies.CanAccessTask)))
            {
                return new ChallengeResult();
            }

            task.Turns.Remove(turn);
            _taskData.Commit();
            return RedirectToAction(nameof(TaskController.Details), "Task", new { id = task.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            var turn = _taskData.GetTurn(id);
            if (null == turn)
            {
                return new NotFoundResult();
            }

            var task = _taskData.GetTaskDetails(turn.TaskId);
            if (null == task)
            {
                return new NotFoundResult();
            }
            if (!await _authorizationService.AuthorizeAsync(User, task, nameof(Policies.CanAccessTask)))
            {
                return new ChallengeResult();
            }

            return View(turn);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, EditTurnViewModel model)
        {
            var turn = _taskData.GetTurn(id);
            if (null == turn)
            {
                return new NotFoundResult();
            }

            var task = _taskData.GetTaskDetails(turn.TaskId);
            if (null == task)
            {
                return new NotFoundResult();
            }
            if (!await _authorizationService.AuthorizeAsync(User, task, nameof(Policies.CanAccessTask)))
            {
                return new ChallengeResult();
            }

            if (!ModelState.IsValid)
            {
                return View(turn);
            }

            turn.Taken = model.Taken;
            turn.Modified = DateTimeOffset.UtcNow;
            _taskData.Commit();
            return RedirectToAction(nameof(TaskController.Details), "Task", new { id = task.Id });
        }
    }
}

src/TurnTrackerAspNetCore/Views/Task/Create.cshtml
@model TurnTrackerAspNetCore.ViewModels.Task.EditTaskViewModel
@{ViewBag.Title = "Create";}
<div>
    <h1>Create Task</h1>
    <form method="post" asp-action="Create" asp-antiforgery="true" class="form-horizontal">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <input type="hidden" asp-for="Owner"/>
        <div class="form-group">
            <label asp-for="Name" class="col-sm-2"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control"/>
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TeamBased" class="col-sm-2 control-label"></label>
            <div class="col-sm-1">
                <input asp-for="TeamBased" class="form-control"/>
            </div>
            <div class="col-sm-9">
                <span class="text-danger" asp-validation-for="TeamBased"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Period" class="col-sm-2 control-label"></label>
            <div class="col-sm-2">
                <input asp-for="Period" class="form-control"/>
                <span class="text-danger" asp-validation-for="Period"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Unit" class="col-sm-2 control-label"></label>
            <div class="col-sm-2">
                <select asp-for="Unit" class="form-control" asp-items="@Html.GetEnumSelectList(typeof(PeriodUnit))"></select>
                <span class="text-danger" asp-validation-for="Unit"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Participants" class="col-sm-2 control-label"></label>
            <div class="col-sm-4">
                <select asp-for="Participants" multiple class="form-control" asp-items="@Model.Users"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2">
                <input class="btn btn-primary" type="submit" value="Save" />
                <a class="btn btn-danger" asp-action="Index">Cancel</a>
            </div>
        </div>
    </form>
</div>

src/TurnTrackerAspNetCore/Views/Task/Details.cshtml
@using System.Threading.Tasks
@using TurnTrackerAspNetCore.Middleware
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@model TurnTrackerAspNetCore.ViewModels.Task.TaskDetailsViewModel
@{
    ViewBag.Title = "Details";
    string cookie;
    if (!HttpContextAccessor.HttpContext.Request.Cookies.TryGetValue(TimezoneOffsetReader.CookieKey, out cookie))
    {
        cookie = "0";
    }
    int minutes;
    int.TryParse(cookie, out minutes);
    var timezoneOffset = TimeSpan.FromMinutes(-minutes);
    ViewBag.TimezoneOffset = timezoneOffset;
}
@if (!string.IsNullOrWhiteSpace(Model.Error))
{
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>@Model.Error
    </div>
}
<h1>@Model.Task.Name</h1>
<div class="row">
    <div class="col-sm-6">
        <div>@(Model.Task.TeamBased ? "Team" : "Individual") Based</div>
        <div><label>Owner</label><span> @(Model.Task.User.DisplayName ?? Model.Task.User.UserName)</span></div>
        <div>
            @if (Model.Task.Period == 0m)
            {
                <span>Non-Periodic</span>
            }
            else
            {
                <span>@Model.Task.Period @Model.Task.Unit</span>
            }
        </div>
        <div><label>Modified</label><span> @Model.Task.Modified.ToOffset(timezoneOffset).ToString("G")</span></div>
        <div><label>Created</label><span> @Model.Task.Created.ToOffset(timezoneOffset).ToString("G")</span></div>
        <div>
            @if (Model.Task.Overdue)
            {
                <strong class="danger">@Model.Task.DueTimeSpan.ToString(@"hh\:mm\:ss") overdue</strong>
            }
            else
            {
                <span>@Model.Task.DueTimeSpan.ToString(@"hh\:mm\:ss") remaining</span>
            }
        </div>
        @if (User.Identity.IsAuthenticated)
        {
            <div class="action-group">
                @if (Model.CanTakeTurn)
                {
                    <form asp-route-id="@Model.Task.Id" asp-antiforgery="true" asp-controller="Turn" asp-action="Take" method="post">
                        <button class="btn btn-primary btn-sm" type="submit" title="Take Turn">
                            <span class="glyphicon glyphicon-plus"></span>
                        </button>
                    </form>
                    <button class="btn btn-primary btn-sm" title="Take Turn at Specific Time" type="button" data-toggle="collapse" data-target="#take-turn-time" aria-expanded="false" aria-controls="take-turn-time">
                        <span class="glyphicon glyphicon-time"></span>
                    </button>
                }
                <a class="btn btn-success btn-sm" asp-action="Edit" asp-route-id="@Model.Task.Id" title="Edit Task">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                @if (Model.CanDeleteTask)
                {
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#delete-task-modal" title="Delete Task">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                }
            </div>
            <div class="collapse" id="take-turn-time">
                <br />
                <div class="well">
                    <form class="form-inline" asp-route-id="@Model.Task.Id" asp-antiforgery="true" asp-controller="Turn" asp-action="Take" method="post">
                        <div class="form-group">
                            <div class="input-group date datetimepicker">
                                <input type="text" name="Time" class="form-control" value="@DateTime.Now" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                        <button class="btn btn-primary" type="submit">Take Turn</button>
                    </form>
                </div>
            </div>
        }
    </div>
    <div class="col-sm-6">
        <h4>Participants</h4>
        @if ((Model.Counts?.Count ?? 0) == 0)
        {
            <p>No participants</p>
        }
        else
        {
            <table class="table table-condensed participants">
                <thead>
                <tr>
                    <th>User</th>
                    <th>Turns</th>
                    <th>Todo</th>
                </tr>
                </thead>
                @{
                    var firstRow = Model.Counts.First();
                }
                <tr class="@(Model.Task.TeamBased ? "" : Model.Task.Overdue ? "danger" : "info")">
                    <td>@firstRow.Name</td>
                    <td>@firstRow.TotalTurns</td>
                    <td>@(Model.MaxTurns - firstRow.TotalTurns)</td>
                </tr>
                @foreach (var row in Model.Counts.Skip(1))
                {
                    <tr>
                        <td>@row.Name</td>
                        <td>@row.TotalTurns</td>
                        <td>@(Model.MaxTurns - row.TotalTurns)</td>
                    </tr>
                }
            </table>
        }
    </div>
</div>
<h4>Turns</h4>
@if ((Model.Task.Turns?.Count ?? 0) == 0)
{
    <p>No turns</p>
}
else
{
    <table class="table table-condensed table-hover table-striped">
        <thead>
        <tr>
            <th>User</th>
            <th>Taken</th>
            <th>Modified</th>
            <th>Created</th>
            @if (User.Identity.IsAuthenticated)
            {
                <th>Actions</th>
            }
        </tr>
        </thead>
        @foreach (var turn in Model.Task.Turns)
        {
            @Html.Partial("_Turn", turn)
        }
    </table>
}

<div class="modal fade" id="delete-task-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Delete Task</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete task '@Model.Task.Name'?</p>
            </div>
            <div class="modal-footer action-group">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                @if (Model.CanDeleteTask)
                {
                    <form asp-route-id="@Model.Task.Id" asp-antiforgery="true" asp-controller="Task" asp-action="Delete" method="post">
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                }
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="delete-turn-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Delete Turn</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete the turn taken by <span id="modal-turn-taker"></span> on <span id="modal-turn-taken"></span>?</p>
            </div>
            <div class="modal-footer action-group">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <form asp-controller="Turn" asp-action="Delete" asp-route-id="0" asp-antiforgery="true" method="post">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

@section footer {
    <span class="timezone">UTC Offset: @timezoneOffset</span>
}

src/TurnTrackerAspNetCore/Views/Task/Edit.cshtml
@model TurnTrackerAspNetCore.ViewModels.Task.EditTaskViewModel
@{
    ViewBag.Title = "Edit Task";
    var label = "contro-label col-sm-2";
    var submit = "col-sm-offset-2";
}
<div>
    <h1>Edit Task</h1>
    <form method="post" asp-action="Edit" asp-antiforgery="true" class="form-horizontal">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="Name" class="@label"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control"/>
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Owner" class="@label"></label>
            <div class="col-sm-3">
                <select asp-for="Owner" asp-items="@Model.Users" class="form-control"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TeamBased" class="@label"></label>
            <div class="col-sm-1">
                <input asp-for="TeamBased" class="form-control pull-left"/>
                <span class="text-danger" asp-validation-for="TeamBased"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Period" class="@label"></label>
            <div class="col-sm-2">
                <input asp-for="Period" class="form-control"/>
                <span class="text-danger" asp-validation-for="Period"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Unit" class="@label"></label>
            <div class="col-sm-2">
                <select asp-for="Unit" asp-items="@Html.GetEnumSelectList(typeof(PeriodUnit))" class="form-control"></select>
                <span class="text-danger" asp-validation-for="Unit"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Participants" class="@label"></label>
            <div class="col-sm-4">
                <select asp-for="Participants" multiple class="form-control" asp-items="@Model.Users"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10 @submit">
                <input class="btn btn-primary" type="submit" value="Save"/>
                <a class="btn btn-danger" asp-action="Details" asp-route-id="@Model.Id">Cancel</a>
            </div>
        </div>
    </form>
</div>

src/TurnTrackerAspNetCore/Views/Task/_Turn.cshtml
@model Turn
<tr>
    <td class="taker">@(Model.User.DisplayName ?? Model.User.UserName)</td>
    <td>
        <span class="taken">@Model.Taken.ToOffset(ViewBag.TimezoneOffset).ToString("G")</span>
        @if (Math.Abs((Model.Taken - Model.Created).TotalHours) > 2)
        {
            <span class="glyphicon glyphicon-alert warning"></span>
        }
    </td>
    <td>
        <span>@Model.Modified.ToOffset(ViewBag.TimezoneOffset).ToString("G")</span>
        @if (Model.Modified != Model.Created)
        {
            <span class="glyphicon glyphicon-alert warning"></span>
        }
    </td>
    <td>@Model.Created.ToOffset(ViewBag.TimezoneOffset).ToString("G")</td>
    @if (User.Identity.IsAuthenticated)
    {
        <td class="action-group">
            <a asp-controller="Turn" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-xs btn-success">
                <span class="glyphicon glyphicon-pencil"></span>
            </a>
            <form class="delete-turn" asp-controller="Turn" asp-action="Delete" asp-route-id="@Model.Id" asp-antiforgery="true" method="post">
                <button type="button" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-trash"></span></button>
            </form>
        </td>
    }
</tr>